name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Validate HTML
      run: |
        echo "Validating HTML structure..."
        # Add HTML validation here later
        
    - name: Check CSS syntax
      run: |
        echo "Checking CSS syntax..."
        # Add CSS validation here later
        
    - name: Lint JavaScript
      run: |
        echo "Linting JavaScript..."
        # Add JS linting here later
        
    - name: Build success
      run: echo "✅ Build completed successfully!"